const now = new Date('2026-07-22T08:30:00.000Z')

function isoDaysAgo(days: number): string {
  const date = new Date(now)
  date.setDate(date.getDate() - days)
  return date.toISOString()
}

export const demoCustomers = [
  {
    id: 'demo-cust-1',
    name: 'Amina Wanjiru',
    phone: '+254700111222',
    email: 'amina@example.com',
    address: 'Kibera, Nairobi',
    customer_type_id: 'residential',
    status: 'active',
    created_at: isoDaysAgo(120),
    updated_at: isoDaysAgo(2),
    customer_types: {
      id: 'residential',
      name: 'Residential',
      tariff_rate_per_liter: 0.12,
    },
  },
  {
    id: 'demo-cust-2',
    name: 'Blue Valley School',
    phone: '+254711333444',
    email: 'admin@bluevalley.ac.ke',
    address: 'Langata Road',
    customer_type_id: 'institutional',
    status: 'active',
    created_at: isoDaysAgo(84),
    updated_at: isoDaysAgo(1),
    customer_types: {
      id: 'institutional',
      name: 'Institutional',
      tariff_rate_per_liter: 0.1,
    },
  },
  {
    id: 'demo-cust-3',
    name: 'Mara Apartments Block C',
    phone: '+254722987654',
    email: 'caretaker@mara-apts.co.ke',
    address: 'South B, Nairobi',
    customer_type_id: 'commercial',
    status: 'suspended',
    created_at: isoDaysAgo(62),
    updated_at: isoDaysAgo(5),
    customer_types: {
      id: 'commercial',
      name: 'Commercial',
      tariff_rate_per_liter: 0.16,
    },
  },
]

export const demoMeters = [
  {
    id: 'demo-meter-1',
    serial_number: 'WM-NAI-0012',
    customer_id: 'demo-cust-1',
    machine_id: 'demo-machine-1',
    install_date: isoDaysAgo(140),
    status: 'active',
    created_at: isoDaysAgo(140),
    updated_at: isoDaysAgo(1),
    customers: { id: 'demo-cust-1', name: 'Amina Wanjiru', phone: '+254700111222' },
  },
  {
    id: 'demo-meter-2',
    serial_number: 'WM-NAI-0044',
    customer_id: 'demo-cust-2',
    machine_id: 'demo-machine-2',
    install_date: isoDaysAgo(90),
    status: 'active',
    created_at: isoDaysAgo(90),
    updated_at: isoDaysAgo(1),
    customers: { id: 'demo-cust-2', name: 'Blue Valley School', phone: '+254711333444' },
  },
  {
    id: 'demo-meter-3',
    serial_number: 'WM-NAI-0069',
    customer_id: 'demo-cust-3',
    machine_id: 'demo-machine-3',
    install_date: isoDaysAgo(70),
    status: 'faulty',
    created_at: isoDaysAgo(70),
    updated_at: isoDaysAgo(6),
    customers: { id: 'demo-cust-3', name: 'Mara Apartments Block C', phone: '+254722987654' },
  },
]

export const demoBills = [
  {
    id: 'demo-bill-1',
    customer_id: 'demo-cust-1',
    meter_id: 'demo-meter-1',
    period_start: isoDaysAgo(45),
    period_end: isoDaysAgo(15),
    liters_billed: 12400,
    amount: 148800,
    status: 'paid',
    due_date: isoDaysAgo(5),
    notes: 'Autogenerated cycle',
    created_at: isoDaysAgo(15),
    updated_at: isoDaysAgo(10),
    customers: { id: 'demo-cust-1', name: 'Amina Wanjiru' },
    meters: { id: 'demo-meter-1', serial_number: 'WM-NAI-0012' },
  },
  {
    id: 'demo-bill-2',
    customer_id: 'demo-cust-2',
    meter_id: 'demo-meter-2',
    period_start: isoDaysAgo(45),
    period_end: isoDaysAgo(15),
    liters_billed: 19800,
    amount: 198000,
    status: 'pending',
    due_date: isoDaysAgo(1),
    notes: 'School term usage',
    created_at: isoDaysAgo(15),
    updated_at: isoDaysAgo(2),
    customers: { id: 'demo-cust-2', name: 'Blue Valley School' },
    meters: { id: 'demo-meter-2', serial_number: 'WM-NAI-0044' },
  },
  {
    id: 'demo-bill-3',
    customer_id: 'demo-cust-3',
    meter_id: 'demo-meter-3',
    period_start: isoDaysAgo(45),
    period_end: isoDaysAgo(15),
    liters_billed: 23300,
    amount: 372800,
    status: 'overdue',
    due_date: isoDaysAgo(8),
    notes: 'Requires follow-up',
    created_at: isoDaysAgo(15),
    updated_at: isoDaysAgo(3),
    customers: { id: 'demo-cust-3', name: 'Mara Apartments Block C' },
    meters: { id: 'demo-meter-3', serial_number: 'WM-NAI-0069' },
  },
]

export const demoPayments = [
  {
    id: 'demo-payment-1',
    bill_id: 'demo-bill-1',
    amount: 148800,
    method: 'mpesa',
    paid_at: isoDaysAgo(11),
    receipt_number: 'MPESA-772891',
    notes: 'Paid in full',
    created_at: isoDaysAgo(11),
    bills: { id: 'demo-bill-1', customer_id: 'demo-cust-1', amount: 148800, status: 'paid' },
  },
  {
    id: 'demo-payment-2',
    bill_id: 'demo-bill-2',
    amount: 50000,
    method: 'bank_transfer',
    paid_at: isoDaysAgo(1),
    receipt_number: 'BANK-10229',
    notes: 'Partial payment',
    created_at: isoDaysAgo(1),
    bills: { id: 'demo-bill-2', customer_id: 'demo-cust-2', amount: 198000, status: 'partial' },
  },
]

export const demoMeterReadings = [
  {
    id: 'demo-reading-1',
    meter_id: 'demo-meter-1',
    reading_value: 12340.55,
    reading_date: isoDaysAgo(12),
    recorded_by: 'demo-operator',
    source: 'automatic',
    notes: 'Normal cycle',
    created_at: isoDaysAgo(12),
    meters: { id: 'demo-meter-1', serial_number: 'WM-NAI-0012' },
  },
  {
    id: 'demo-reading-2',
    meter_id: 'demo-meter-2',
    reading_value: 21440.2,
    reading_date: isoDaysAgo(9),
    recorded_by: 'demo-operator',
    source: 'automatic',
    notes: 'Campus block A',
    created_at: isoDaysAgo(9),
    meters: { id: 'demo-meter-2', serial_number: 'WM-NAI-0044' },
  },
  {
    id: 'demo-reading-3',
    meter_id: 'demo-meter-3',
    reading_value: 19670.05,
    reading_date: isoDaysAgo(7),
    recorded_by: 'field-tech',
    source: 'manual',
    notes: 'Signal drop fallback',
    created_at: isoDaysAgo(7),
    meters: { id: 'demo-meter-3', serial_number: 'WM-NAI-0069' },
  },
]

export const demoMachines = [
  {
    id: 'demo-machine-1',
    serial_number: 'MCH-NAI-0120',
    name: 'Kibera Water Point A',
    address: 'Kibera, Nairobi',
    status: 'active',
    tank_capacity_liters: 5000,
    last_seen_at: isoDaysAgo(0),
    device_provisioned_at: isoDaysAgo(140),
  },
  {
    id: 'demo-machine-2',
    serial_number: 'MCH-NAI-0248',
    name: 'Blue Valley School Borehole',
    address: 'Langata Road',
    status: 'connected',
    tank_capacity_liters: 8000,
    last_seen_at: isoDaysAgo(0),
    device_provisioned_at: isoDaysAgo(95),
  },
  {
    id: 'demo-machine-3',
    serial_number: 'MCH-NAI-0312',
    name: 'South B Block C',
    address: 'South B',
    status: 'under_maintenance',
    tank_capacity_liters: 6000,
    last_seen_at: isoDaysAgo(3),
    device_provisioned_at: isoDaysAgo(75),
  },
]

export const demoSales = [
  {
    id: 1,
    machine_id: 'demo-machine-1',
    liters: 120,
    amount_paid: 1450,
    payment_method: 'mpesa',
    sold_at: isoDaysAgo(0),
  },
  {
    id: 2,
    machine_id: 'demo-machine-1',
    liters: 86,
    amount_paid: 980,
    payment_method: 'cash',
    sold_at: isoDaysAgo(0),
  },
  {
    id: 3,
    machine_id: 'demo-machine-2',
    liters: 240,
    amount_paid: 2600,
    payment_method: 'bank_transfer',
    sold_at: isoDaysAgo(0),
  },
]

export const demoBusinessProfile = {
  id: 'demo-business-1',
  business_name: 'WaterFlow Utility Services',
  tagline: 'Reliable water operations for every community',
  logo_url: null,
  currency_code: 'KES',
  updated_at: now.toISOString(),
}

export const demoCustomerTypes = [
  { id: 'residential', name: 'Residential', tariff_rate_per_liter: 0.12, description: 'Household tariff' },
  { id: 'commercial', name: 'Commercial', tariff_rate_per_liter: 0.16, description: 'Business tariff' },
  { id: 'institutional', name: 'Institutional', tariff_rate_per_liter: 0.1, description: 'School/hospital tariff' },
]

export const demoRoles = [
  { id: 'role-admin', name: 'Admin', description: 'Full system access', permissions: { can_read: true, can_write: true, can_bill: true } },
  { id: 'role-supervisor', name: 'Supervisor', description: 'Operations oversight', permissions: { can_read: true, can_write: true, can_bill: true } },
  { id: 'role-tech', name: 'Field Technician', description: 'Maintenance and field work', permissions: { can_read: true, can_write: false, can_bill: false } },
]

export const demoEmployees = [
  { id: 'emp-1', name: 'Jane Otieno', email: 'jane.otieno@waterflow.demo', phone: '+254711100001', role_id: 'role-supervisor', status: 'active', hire_date: '2025-02-10', roles: { id: 'role-supervisor', name: 'Supervisor' } },
  { id: 'emp-2', name: 'Brian Kariuki', email: 'brian.kariuki@waterflow.demo', phone: '+254711100002', role_id: 'role-tech', status: 'active', hire_date: '2025-08-21', roles: { id: 'role-tech', name: 'Field Technician' } },
  { id: 'emp-3', name: 'Muthoni Wairimu', email: 'muthoni.wairimu@waterflow.demo', phone: '+254711100003', role_id: 'role-admin', status: 'inactive', hire_date: '2024-11-02', roles: { id: 'role-admin', name: 'Admin' } },
]

export const demoSuppliers = [
  { id: 'sup-1', name: 'AquaTech Supplies', contact_person: 'Paul Ndegwa', phone: '+254733200001', email: 'paul@aquatech.demo', address: 'Industrial Area', status: 'active' },
  { id: 'sup-2', name: 'PlumbPro Distributors', contact_person: 'Sarah Waceke', phone: '+254733200002', email: 'sarah@plumbpro.demo', address: 'Mombasa Road', status: 'active' },
]

export const demoStockItems = [
  { id: 'stock-1', name: 'Flow Sensor', category: 'electronics', quantity: 14, unit: 'piece', reorder_level: 6, unit_cost: 2500, supplier_id: 'sup-1', suppliers: { id: 'sup-1', name: 'AquaTech Supplies' } },
  { id: 'stock-2', name: 'Valve Kit', category: 'fittings', quantity: 8, unit: 'piece', reorder_level: 12, unit_cost: 1200, supplier_id: 'sup-2', suppliers: { id: 'sup-2', name: 'PlumbPro Distributors' } },
  { id: 'stock-3', name: 'Battery Pack', category: 'power', quantity: 22, unit: 'piece', reorder_level: 8, unit_cost: 4200, supplier_id: 'sup-1', suppliers: { id: 'sup-1', name: 'AquaTech Supplies' } },
]

export const demoRepairs = [
  { id: 'repair-1', machine_id: 'demo-machine-1', meter_id: 'demo-meter-1', description: 'Replace pressure valve', status: 'in_progress', priority: 'high', reported_at: isoDaysAgo(2), assigned_to: 'emp-2', machines: { id: 'demo-machine-1', name: 'Kibera Water Point A' }, meters: { id: 'demo-meter-1', serial_number: 'WM-NAI-0012' } },
  { id: 'repair-2', machine_id: 'demo-machine-3', meter_id: 'demo-meter-3', description: 'Seal meter housing', status: 'open', priority: 'normal', reported_at: isoDaysAgo(1), assigned_to: 'emp-2', machines: { id: 'demo-machine-3', name: 'South B Block C' }, meters: { id: 'demo-meter-3', serial_number: 'WM-NAI-0069' } },
]

export const demoLeakReports = [
  { id: 'leak-1', machine_id: 'demo-machine-2', meter_id: 'demo-meter-2', description: 'Underground leak near school boundary', severity: 'high', status: 'confirmed', estimated_loss_liters: 320, reported_at: isoDaysAgo(3), machines: { id: 'demo-machine-2', name: 'Blue Valley School Borehole' }, meters: { id: 'demo-meter-2', serial_number: 'WM-NAI-0044' } },
  { id: 'leak-2', machine_id: 'demo-machine-1', meter_id: 'demo-meter-1', description: 'Valve dripping from junction', severity: 'medium', status: 'reported', estimated_loss_liters: 95, reported_at: isoDaysAgo(1), machines: { id: 'demo-machine-1', name: 'Kibera Water Point A' }, meters: { id: 'demo-meter-1', serial_number: 'WM-NAI-0012' } },
]
